Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 21, in <module>
    print(xy)
NameError: name 'xy' is not defined. Did you mean: 'xyz'?

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 29, in <module>
    print(d[2])
KeyError: 2

================= RESTART: C:/Python310/python_program/error.py ================
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 1, in <module>
    import OS
ModuleNotFoundError: No module named 'OS'

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 37, in <module>
    print(d[7])
IndexError: list index out of range

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 37, in <module>
    print(d[7])   #IndexError: list index out of range
IndexError: list index out of range

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 40, in <module>
    x = 2/0
ZeroDivisionError: division by zero

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 42, in <module>
    x = 1/False
ZeroDivisionError: division by zero

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
97

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
97
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 46, in <module>
    print(ord(1))
TypeError: ord() expected string of length 1, but int found

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
97
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 47, in <module>
    print(ord("abc"))
TypeError: ord() expected a character, but string of length 3 found

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
97
2

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
97
2
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 51, in <module>
    x = int(r)
NameError: name 'r' is not defined

================= RESTART: C:/Python310/python_program/error.py ================
11.0
7.5
9
10
3
97
2
Traceback (most recent call last):
  File "C:/Python310/python_program/error.py", line 51, in <module>
    x = int('r')
ValueError: invalid literal for int() with base 10: 'r'
